sudo: false

language: go

services:
  - docker

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - sudo apt-get install -y pkg-config
  - bash dependencies.sh
  - docker-compose up -d --build && sleep 30
  - make check
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
